# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass
from omegaconf import MISSING


@dataclass
class CelebaKCConf:
    _target_: str = "extinct.components.models.CelebaKC"
    lr: float = MISSING
    weight_decay: float = MISSING
    lr_gamma: float = MISSING
    batch_norm: bool = True


@dataclass
class LaftrConf:
    _target_: str = "extinct.components.models.Laftr"
    lr: float = MISSING
    weight_decay: float = MISSING
    lr_gamma: float = MISSING
    disc_steps: int = MISSING
    fairness: str = MISSING
    recon_weight: float = MISSING
    clf_weight: float = MISSING
    adv_weight: float = MISSING


@dataclass
class CelebaErmConf:
    _target_: str = "extinct.components.models.CelebaErm"
    lr: float = MISSING
    weight_decay: float = MISSING
    lr_gamma: float = MISSING
    batch_norm: bool = True


@dataclass
class DannConf:
    _target_: str = "extinct.components.models.Dann"
    lr: float = MISSING
    weight_decay: float = MISSING
    grl_lambda: float = 1.0
