defaults:
  - /schema/model: dino

lr: 5.e-4
warmup_iters: 3000
min_lr: 1.e-6
freeze_last_layer: 100
patch_size: 8
out_dim: 65636
norm_last_layer: True
use_bn_in_head: False
momentum_teacher: 0.996
teacher_temp: 0.04
warmup_teacher_temp_iters: 0
eval_method: lin_clf
num_eval_blocks: 1
lr_eval: 1.e-4
max_steps: ${trainer.max_steps}
dm_batch_size: ${data.batch_size}
local_crops_number: ${data.local_crops_number}
