# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class CelebaDataModuleConf:
    _target_: str = "extinct.datamodules.CelebaDataModule"
    data_dir: Optional[str] = None
    image_size: int = 64
    batch_size: int = 32
    num_workers: int = 0
    val_split: float = 0.2
    test_split: float = 0.2
    y_label: str = "Smiling"
    s_label: str = "Male"
    seed: int = 0
    persist_workers: bool = False
    stratified_sampling: bool = False
    sample_with_replacement: bool = True
    data_aug: bool = False
